version: '3'
services:
  laravel:
    image: laravel
    restart: always
    build:
      context: .
      args:
        ENV: test
    container_name: laravel
    volumes:
      - ${PWD}/storage:/app/storage
    ports:
      - '8000:8000'
    entrypoint:
      - php
      - artisan
      - serve
      - --host=0.0.0.0
