version: '3'
services:
  laravel:
    image: laravel
    restart: always
    build:
      context: .
      args:
        ENV: production
    container_name: laravel
    volumes:
      - ${PWD}/storage:/app/storage
    ports:
      - '8000:8000'
    entrypoint:
      - php
      - artisan
      - serve
      - --host=0.0.0.0
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0/v1/health']
      retries: 3
      timeout: 5s
