version: '3'
services:
  laravel:
    image: laravel
    restart: always
    build:
      context: .
      args:
        ENV: testing
    container_name: laravel
    volumes:
      - ${PWD}/storage:/app/storage
    ports:
      - '8000:8000'
    entrypoint:
      - php
      - -S
      - 0.0.0.0:8000
      - -t
      - public
